### ISSUE TITLE
Update dependencies to use last version of inappwebview

### ISSUE THREAD

**Issue by Chralu** [pasteque-org/archethic-dart#1]
Update

- `graphql`

```
graphql:
    git:
      url: https://github.com/redDwarf03/graphql-flutter.git
      ref: Web_socket_channel_301
      path: packages/graphql
```
